embeds:
  colors:
    primary: 5793266
    success: 5763719
    warning: 16705372
    error: 15548997
    info: 3908957
  footer: {}
  timestamp: true
pagination:
  timeout: 120000
  itemsPerPage: 10
confirmation:
  timeout: 30000
